export type PlacementType = 'bottom' | 'top' | 'left' | 'right'
export type StateType = 'default' | 'primary' | 'success' | 'warning' | 'danger'
export type SizeType = 'large' | 'middle' | 'small'
export type ButtonShapeType = 'rectangle' | 'round' | 'circle' | 'square'
export type ButtonPatternType =
  | 'default'
  | 'solid'
  | 'dashed'
  | 'borderless'
  | 'gradient'
export type TagPatternType = 'light' | 'dark' | 'plain'
export type AvatarShapeType = 'circle' | 'square'
export type ColorStyle =
  | 'DustRed'
  | 'Volcano'
  | 'SunsetOrange'
  | 'CalendulaGold'
  | 'SunriseYellow'
  | 'Lime'
  | 'PolarGreen'
  | 'Cyan'
  | 'DaybreakBlue'
  | 'GeekBlue'
  | 'GoldenPurple'
  | 'Magenta'
